[package]
name = "humantime"
description = """A parser and formatter for std::time::{Duration, SystemTime}"""
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["time", "human", "human-friendly", "parser", "duration"]
homepage = "https://github.com/chronotope/humantime"
repository = "https://github.com/chronotope/humantime"
documentation = "https://docs.rs/humantime"
version = "2.2.0"
edition = "2021"
categories = ["date-and-time"]

[features]
mu = []

[dependencies]
chrono = {version = "0.4", default-features = false}

[dev-dependencies]
bencher = "0.1.5"
chrono = "0.4"
rand = "0.9"

[[bench]]
name = "datetime_format"
harness = false

[[bench]]
name = "datetime_parse"
harness = false

[lints.clippy]
std_instead_of_core = "forbid"
std_instead_of_alloc = "forbid"